### ISSUE TITLE
Very laggy AllProjectAssetsReferencesWindow

### ISSUE THREAD

**Issue by STARasGAMES** [AlexeyPerov/Unity-Dependencies-Hunter#3]
I ran the analysis and I got 874 unused assets:
![image](https://user-images.githubusercontent.com/23558898/125583196-d3f73ed4-bf8d-4aba-93ab-cd37d62966a8.png)

I have a quite powerful CPU but it can't handle this list of fields :)
I'm getting like 1 FPS or less with this window

Profiler shows strange things. I don't use FMOD but it's here o_O.
![image](https://user-images.githubusercontent.com/23558898/125586579-8d11996e-674f-4d6f-be65-29fc4cec145a.png)

In other frames, spikes go from UIElements, etc

**Comment by AlexeyPerov** [comment]
That happens due to the nature of Unity Editor GUI when it comes to rendering such large lists.
Some folks use something like loop/wrap/dynamic lists for such tasks but I think that is too much for such a plugin.

So I have added pagination in this commit 47ae2ec6dd7a4c5698b59c0ed3fd0c95e1c33232
It will allow you to render 50 items at a moment (the number is customizable)
